"""Add created_at to user_devices table

Revision ID: 07a988d35dcb
Revises: 36b10c50ac32
Create Date: 2025-04-04 09:05:44.842705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '07a988d35dcb'
down_revision = '36b10c50ac32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'created_at')
    # ### end Alembic commands ###
