"""removed password and azure adb2c

Revision ID: 0aeb255d4595
Revises: ae5e86e89511
Create Date: 2025-02-27 18:32:18.615114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeb255d4595'
down_revision = 'ae5e86e89511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
