"""added autoincrement key for follow id

Revision ID: 12660c9da995
Revises: c8cdf6ef0757
Create Date: 2025-03-28 16:43:59.555634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '12660c9da995'
down_revision = 'c8cdf6ef0757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'following_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'following_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
