"""update table errors

Revision ID: 1728312d24cb
Revises: a6026effb838
Create Date: 2025-03-04 11:32:12.057162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1728312d24cb'
down_revision = 'a6026effb838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_old')
    op.drop_table('UserContentInteractions')
    op.drop_table('Users_temp')
    op.drop_table('Media')
    op.create_foreign_key(None, 'Comments', 'Posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'Comments', 'Users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Follows', 'Users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'Follows', 'Users', ['following_id'], ['id'])
    op.create_foreign_key(None, 'Likes', 'Posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'Likes', 'Users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Posts', 'Users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'post_hashtags', 'Hashtags', ['hashtag_id'], ['id'])
    op.create_foreign_key(None, 'post_hashtags', 'Posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post_likes', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_likes', 'Posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.drop_constraint(None, 'post_hashtags', type_='foreignkey')
    op.drop_constraint(None, 'post_hashtags', type_='foreignkey')
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    op.drop_constraint(None, 'Follows', type_='foreignkey')
    op.drop_constraint(None, 'Follows', type_='foreignkey')
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.drop_constraint(None, 'Comments', type_='foreignkey')
    op.create_table('Media',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blob_url', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('upload_time', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('description', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('share_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.NVARCHAR(length=1, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('video_duration_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_id', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('media_id', name='PK_Media')
    )
    op.create_table('Users_temp',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('followers_count', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('following_count', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__Users_te__3213E83F998F88C9')
    )
    op.create_table('UserContentInteractions',
    sa.Column('interaction_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('media_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('timestamp', mssql.DATETIME2(), autoincrement=False, nullable=False),
    sa.Column('watch_time_in_seconds', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('completion_rate_in_percentage', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.media_id'], name='FK_UserContentInteractions_Media'),
    sa.PrimaryKeyConstraint('interaction_id', name='PK__UserCont__605F8FE6A02D019D')
    )
    op.create_table('users_old',
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('followers_count', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('following_count', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('acs_identity_id', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
