"""Add media interactions table

Revision ID: 1a714d4c9da3
Revises: 7c95ac4ba2bb
Create Date: 2025-04-08 06:38:06.991360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1a714d4c9da3'
down_revision = '7c95ac4ba2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass