"""Add post attributes to user_saved_posts

Revision ID: 1fc5622441a8
Revises: 12660c9da995
Create Date: 2025-03-28 19:16:07.808860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1fc5622441a8'
down_revision = '12660c9da995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved_posts', sa.Column('content', sa.String(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('media', sa.String(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('location', sa.String(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('share_count', sa.Integer(), nullable=True))
    op.add_column('user_saved_posts', sa.Column('visibility', sa.Enum('public', 'private', 'friends', name='visibilityenum'), nullable=False, server_default='public'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_saved_posts', 'visibility')
    op.drop_column('user_saved_posts', 'share_count')
    op.drop_column('user_saved_posts', 'comments_count')
    op.drop_column('user_saved_posts', 'likes_count')
    op.drop_column('user_saved_posts', 'location')
    op.drop_column('user_saved_posts', 'media')
    op.drop_column('user_saved_posts', 'content')
    # ### end Alembic commands ###
