"""Rectified relational attribute

Revision ID: 2e3b61137843
Revises: 6528082bf4c2
Create Date: 2025-02-21 01:10:08.138910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3b61137843'
down_revision = '6528082bf4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Likes_id', table_name='Likes')
    op.drop_column('Likes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Likes', sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True))
    op.create_index('ix_Likes_id', 'Likes', ['id'], unique=False)
    # ### end Alembic commands ###
