"""Add user_devices table

Revision ID: 36b10c50ac32
Revises: db490bfbb79e
Create Date: 2025-04-04 08:35:57.637701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.orm import Session
import uuid

# revision identifiers, used by Alembic.
revision = '36b10c50ac32'
down_revision = 'db490bfbb79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token')
    op.drop_column('users', 'platform')
    # Transfer data from User to UserDevice
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###