"""Add blocked users table

Revision ID: 392427f34541
Revises: c2c7f78b3a02
Create Date: 2025-03-13 15:01:14.167754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '392427f34541'
down_revision = 'c2c7f78b3a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=True),
    sa.Column('blocked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_users_id'), 'blocked_users', ['id'], unique=False)
    op.alter_column('posts', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.drop_index(op.f('ix_blocked_users_id'), table_name='blocked_users')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
