"""Fix relationships

Revision ID: 44efe388f791
Revises: 2e3b61137843
Create Date: 2025-02-21 05:36:38.817391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44efe388f791'
down_revision = '2e3b61137843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Hashtags_name', table_name='Hashtags')
    op.drop_constraint('FK__Likes__post_id__30792600', 'Likes', type_='foreignkey')  # You need to replace the name of the foreign key constraint
    op.drop_constraint('FK__Likes__user_id__316D4A39', 'Likes', type_='foreignkey')
    op.drop_constraint('PK__Likes__3213E83FEEC9E398', 'Likes', type_='primary')  # Replace with your actual constraint name
    op.drop_column('Likes', 'id')
    op.drop_constraint('FK__post_like__user___3726238F', 'post_likes', type_='foreignkey')
    op.drop_constraint('FK__post_like__post___381A47C8', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_likes', 'Posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('FK__post_like__post___381A47C8', 'post_likes', 'Posts', ['post_id'], ['id'])
    op.create_foreign_key('FK__post_like__user___3726238F', 'post_likes', 'Users', ['user_id'], ['id'])
    op.add_column('Likes', sa.Column('id', sa.Integer, primary_key=True, autoincrement=True))
    op.create_primary_key('PK__Likes__3213E83FEEC9E398', 'Likes', ['id'])
    op.create_index('ix_Hashtags_name', 'Hashtags', ['name'], unique=False)
    # ### end Alembic commands ###
