"""add visibility to posts

Revision ID: 46e2e4318bb4
Revises: 6b1dc9dd58a9
Create Date: 2025-03-28 09:37:32.596805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '46e2e4318bb4'
down_revision = '6b1dc9dd58a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('visibility', sa.Enum('public', 'private', 'friends', name='visibilityenum'), nullable=False, server_default="public"))
    op.alter_column("posts", "visibility", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'visibility')
    sa.Enum(name="visibilityenum").drop(op.get_bind())
    # ### end Alembic commands ###
