"""Rectified attribute

Revision ID: 6528082bf4c2
Revises: 5f37e9470caf
Create Date: 2025-02-20 17:45:24.542106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6528082bf4c2'
down_revision = '5f37e9470caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('Comments', 'created_dt')
    op.add_column('Posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('Posts', 'created_dt')
    op.add_column('Users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('Users', 'created_dt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created_dt', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'created_at')
    op.add_column('Posts', sa.Column('created_dt', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('Posts', 'created_at')
    op.add_column('Comments', sa.Column('created_dt', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('Comments', 'created_at')
    # ### end Alembic commands ###
