"""Add notification flags to UserDevice

Revision ID: 7c95ac4ba2bb
Revises: 07a988d35dcb
Create Date: 2025-04-08 05:17:39.300678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7c95ac4ba2bb'
down_revision = '07a988d35dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('notify_likes', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_comments', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_share', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_calls', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_messages', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_follow', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_posts', sa.Boolean(), nullable=True))
    op.add_column('user_devices', sa.Column('notify_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'notify_status')
    op.drop_column('user_devices', 'notify_posts')
    op.drop_column('user_devices', 'notify_follow')
    op.drop_column('user_devices', 'notify_messages')
    op.drop_column('user_devices', 'notify_calls')
    op.drop_column('user_devices', 'notify_share')
    op.drop_column('user_devices', 'notify_comments')
    op.drop_column('user_devices', 'notify_likes')
    # ### end Alembic commands ###
