"""updated activities table

Revision ID: a6026effb838
Revises: 0aeb255d4595
Create Date: 2025-02-28 07:48:44.946517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6026effb838'
down_revision = '0aeb255d4595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('liked_media', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('commented_media', sa.String(), nullable=True))
    op.drop_column('activities', 'liked_post_image')
    op.drop_column('activities', 'commented_post_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('commented_post_image', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('liked_post_image', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('activities', 'commented_media')
    op.drop_column('activities', 'liked_media')
    # ### end Alembic commands ###
