"""updated login and register

Revision ID: ae5e86e89511
Revises: 44efe388f791
Create Date: 2025-02-25 06:37:22.532738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5e86e89511'
down_revision = '44efe388f791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Likes', 'Users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Likes', 'Posts', ['post_id'], ['id'])
    # op.drop_column('Users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hashed_password', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    # ### end Alembic commands ###
