"""Modify media interactions table and add multiple reports

Revision ID: af1285905239
Revises: 1a714d4c9da3
Create Date: 2025-04-10 04:14:51.427606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'af1285905239'
down_revision = '1a714d4c9da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('report_count', sa.Integer(), nullable=True))
    op.add_column('media_interactions', sa.Column('media_type', sa.Enum('image', 'video', name='mediatypeenum'), nullable=False))
    op.add_column('media_interactions', sa.Column('video_length', sa.Integer(), nullable=True))
    op.add_column('media_interactions', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.add_column('media_interactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('media_interactions', 'timestamp')
    op.add_column('posts', sa.Column('report_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('report_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'report_count')
    op.drop_column('posts', 'report_count')
    op.add_column('media_interactions', sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_column('media_interactions', 'created_at')
    op.drop_column('media_interactions', 'skipped')
    op.drop_column('media_interactions', 'video_length')
    op.drop_column('media_interactions', 'media_type')
    op.drop_column('comments', 'report_count')
    # ### end Alembic commands ###
