"""update tables

Revision ID: b86ac01ee959
Revises: ab58f6881e07
Create Date: 2025-03-07 16:44:30.398410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b86ac01ee959'
down_revision = 'ab58f6881e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_column('likes', 'created_at')
    op.drop_column('likes', 'id')
    # ### end Alembic commands ###
