"""add multiple reports tables

Revision ID: bbe985dfb239
Revises: af1285905239
Create Date: 2025-04-10 04:29:32.774843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'bbe985dfb239'
down_revision = 'af1285905239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'report_posts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('post_id', sa.Integer(), sa.ForeignKey("posts.id", ondelete="CASCADE"), nullable=False),
        sa.Column('reported_by', sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column('reason', sa.Enum('spam', 'abuse', 'nudity', 'hate_speech', 'misinformation', 'harassment', 'other', name='reportreasonenum'), nullable=False, default='other', server_default='other'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('post_id', 'reported_by', name='uix_post_report')
    )
    op.create_table(
        'report_users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey("users.id", ondelete="NO ACTION"), nullable=False),
        sa.Column('reported_by', sa.Integer(), sa.ForeignKey("users.id", ondelete="NO ACTION"), nullable=False),
        sa.Column('reason', sa.Enum('spam', 'abuse', 'nudity', 'hate_speech', 'misinformation', 'harassment', 'other', name='reportreasonenum'), nullable=False, default='other', server_default='other'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'reported_by', name='uix_user_report')
    )
    op.create_table(
        'report_comments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('comment_id', sa.Integer(), sa.ForeignKey("comments.id", ondelete="CASCADE"), nullable=False),
        sa.Column('reported_by', sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column('reason', sa.Enum('spam', 'abuse', 'nudity', 'hate_speech', 'misinformation', 'harassment', 'other', name='reportreasonenum'), nullable=False, default='other', server_default='other'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('comment_id', 'reported_by', name='uix_comment_report')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_comments')
    op.drop_table('report_users')
    op.drop_table('report_posts')
    # ### end Alembic commands ###
