"""Add share_count column to posts

Revision ID: c2c7f78b3a02
Revises: b86ac01ee959
Create Date: 2025-03-12 15:36:52.299358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c2c7f78b3a02'
down_revision = 'b86ac01ee959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('share_count', sa.Integer(), nullable=True))
    op.add_column('user_shared_posts', sa.Column('sender_user_id', sa.Integer(), nullable=False))
    op.add_column('user_shared_posts', sa.Column('receiver_user_id', sa.Integer(), nullable=False))
    op.add_column('user_shared_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_shared_posts_id'), 'user_shared_posts', ['id'], unique=False)
    op.drop_constraint('FK__user_shar__user___08F5448B', 'user_shared_posts', type_='foreignkey')
    op.drop_constraint('FK__user_shar__post___09E968C4', 'user_shared_posts', type_='foreignkey')
    op.create_foreign_key(None, 'user_shared_posts', 'users', ['receiver_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_shared_posts', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_shared_posts', 'users', ['sender_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_shared_posts', 'shared_at')
    op.drop_column('user_shared_posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shared_posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_shared_posts', sa.Column('shared_at', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_shared_posts', type_='foreignkey')
    op.drop_constraint(None, 'user_shared_posts', type_='foreignkey')
    op.drop_constraint(None, 'user_shared_posts', type_='foreignkey')
    op.create_foreign_key('FK__user_shar__post___09E968C4', 'user_shared_posts', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('FK__user_shar__user___08F5448B', 'user_shared_posts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_shared_posts_id'), table_name='user_shared_posts')
    op.drop_column('user_shared_posts', 'created_at')
    op.drop_column('user_shared_posts', 'receiver_user_id')
    op.drop_column('user_shared_posts', 'sender_user_id')
    op.drop_column('posts', 'share_count')
    # ### end Alembic commands ###
