"""updated likes and follow table

Revision ID: c8cdf6ef0757
Revises: 90ddba65f14d
Create Date: 2025-03-28 15:25:43.753390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c8cdf6ef0757'
down_revision = '90ddba65f14d'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with NULL allowed
    op.add_column('follows', sa.Column('id', sa.Integer(), nullable=True))

    # Set the 'id' column to a default value (e.g., 0) or logic
    op.execute('UPDATE follows SET id = 0')

    # Alter the column to be non-nullable after the data is populated
    op.alter_column('follows', 'id', nullable=False, existing_type=sa.Integer())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'following_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###
