"""Add device_token and platform to User model

Revision ID: d1dbcf39652e
Revises: 392427f34541
Create Date: 2025-03-24 09:31:21.868602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd1dbcf39652e'
down_revision = '392427f34541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('platform', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform')
    op.drop_column('users', 'device_token')
    # ### end Alembic commands ###
