"""Added account_type attribute to user

Revision ID: db490bfbb79e
Revises: 1fc5622441a8
Create Date: 2025-04-02 05:36:46.308314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'db490bfbb79e'
down_revision = '1fc5622441a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.Enum('PUBLIC', 'PRIVATE', name='accounttypeenum'), nullable=False, server_default='PUBLIC'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
