"""
Django settings for Vreels project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
AZURE_CREDENTIALS = os.getenv("AZURE_CREDENTIALS")
AZURE_WEBAPP_NAME = os.getenv("AZURE_WEBAPP_NAME")
AZURE_RESOURCE_GROUP = os.getenv("AZURE_RESOURCE_GROUP")
AZURE_SUBSCRIPTION_ID = os.getenv("AZURE_SUBSCRIPTION_ID")
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS")

# Azure notifications
NOTIFICATION_HUB_NAME = os.getenv("NOTIFICATION_HUB_NAME")
NOTIFICATION_HUB_CONNECTION_STRING = os.getenv("NOTIFICATION_HUB_CONNECTION_STRING")
AZURE_NAMESPACE = os.getenv("AZURE_NAMESPACE")  # Example: "yourappnamespace"
AZURE_ACCESS_KEY = os.getenv("AZURE_ACCESS_KEY")  # From Access Policies
AZURE_HUB_NAME = os.getenv("NOTIFICATION_HUB_NAME") # Notification Hub name
    
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Vreels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Vreels.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# settings.py (Django)
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'vreeels_django_database',
        'USER': 'sqladmin',
        'PASSWORD': 'MnkLlc@25',
        'HOST': 'sqlddatabbasedemo.database.windows.net',
        # 'NAME': 'vreels-database',
        # 'USER': 'Vreels_api',
        # 'PASSWORD': 'Vre2ls%23A1pi%402025',
        # 'HOST': 'vreels-database-server.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server'
        },
    }
}

# Azure Storage for media files
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")

SITE_ID = 1
SITE_URL = "http://127.0.0.1:8000"

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # For Deployment
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # For Development
# EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server
# EMAIL_PORT = 587  # Use 465 for SSL
# EMAIL_USE_TLS = True  # Use TLS for secure connection
# EMAIL_HOST_USER = 'palle.saisneha@gmail.com'  # Your email address
# EMAIL_HOST_PASSWORD = 'muvr mwlc wjdu dhll'  # Your email password
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AZURE_CONTAINER = '$logs'